### PR TITLE
changed the interface, using voiceactivity and added an Node Error in…

### PR DESCRIPTION
**Pull request by Flowr-es**
… Error case

### CODE REVIEW

**Comment by nekuz0r** [comment]
@MexXxo I am not really fan of `voiceactivity`, i think it's misleading.
It's just that it sound like you are indeed expecting voice activity on the event.

From the comments in the header file of the C++ API,
the return values of `SnowboyDetect::RunDetection` 
`0`: does not imply there was some voice activity detected. Just sound and nothing was recognizable in that sound.
`-2` means there was no sound activity at all (silence).

Same apply to the `voice` boolean.

I can't come with a better name right now, but i will continue to think of something ;)

**Comment by evancohen** [comment]
\+ @nekuz0r

Hey @MexXxo, I don't think `snowboy` is actually detecting "speech" just noise (please correct me if I'm wrong) - so I'm not sure if an event handler `"voiceactivity"` makes sense here (maybe you call it `"sound"`?). Either way, having distinct events makes the code you have to write easier and a bit more clear...

**Seperate event handlers**

``` javascript
detector.on('silence', function () {
  console.log('silence');
});

detector.on('noise', function () {
  console.log('noise');
});
```

**Combined event handlers**

``` javascript
detector.on('sound', function (hasSound) {
  if (hasSound) {
    console.log('noise');
  } else {
    console.log('silence');
  }
});
```

IMHO the separate handlers makes it cleaner and easier to use because you aren't forced to check a variable every time.

As for the error detection, can we bubble up what the actual error was from the native module? I don't think there's a point of adding a hard coded string if we only have one error type.

**Comment by nekuz0r** [comment]
@evancohen 

The C++ API does not provides more information on error.

`SnowboyDetect::RunDetection` returns `-1` on error, that's all.

Documentation/Comments does not specify what can trigger an error.

I think it may trigger an error if the audio data properties don't match (channels, sample rate, bits per sample)

**Comment by evancohen** [comment]
@MexXxo @nekuz0r Maybe it doesn't work this way, but I think we can have some slightly more intelligent errors by using something like [`Nan::ThrowError`](https://github.com/nodejs/nan/blob/master/doc/errors.md#api_nan_throw_error) and a try/catch on the native side?

I can intentionally force an error by passing in a model that doesn't exist, which barfs all over but has some useful info:

```
ERROR (Input():snowboy-io.cc:266) Fail to open input file "resources/snaowboy.umdl"
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ERROR (Input():snowboy-io.cc:266) Fail to open input file "resources/snaowboy.umdl"

[stack trace: ]
0   snowboy.node                        0x0000000102d8b6ce _ZN7snowboy13GetStackTraceEv + 94
1   snowboy.node                        0x0000000102d8c3c7 _ZN7snowboy13SnowboyLogMsgD2Ev + 487
2   snowboy.node                        0x0000000102d8fb74 _ZN7snowboy5InputC2ERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE + 612
3   snowboy.node                        0x0000000102d8202e _ZN7snowboy14PipelineDetect14ClassifyModelsERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEPS7_SA_ + 286
4   snowboy.node                        0x0000000102d81e9d _ZN7snowboy14PipelineDetect8SetModelERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE + 61
.
.
.
7   snowboy.node                        0x0000000102d4e952 _ZN13SnowboyDetect3NewERKN3Nan20FunctionCallbackInfoIN2v85ValueEEE + 1254
8   snowboy.node                        0x0000000102d4fa03 _ZN3Nan3impL23FunctionCallbackWrapperERKN2v820FunctionCallbackInfoINS1_5ValueEEE + 131
9   node                                0x0000000100184e35 _ZN2v88internal25FunctionCallbackArguments4CallEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEE + 373
10  node                                0x00000001001de9ff _ZN2v88internalL30Builtin_HandleApiCallConstructEiPPNS0_6ObjectEPNS0_7IsolateE + 1375
11  ???                                 0x0000044d8fa0961b 0x0 + 4731168658971

    at Error (native)
    at new SnowboyDetect (/Users/evan/Git/snowboy/lib/node/index.js:62:29)
    at Object.<anonymous> (/Users/evan/Git/snowboy/examples/Node/demo.js:12:11)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
```

Maybe the best solution is to check for the file on the JS side before passing it down, but it might be nice if we had a more generic way to deal with native exceptions. Either of you familiar with this?

**Comment by Flowr-es** [comment]
Hi, 
sorry I was a bit busy the last days.

From the snowboy docs ( https://snowboy.kitt.ai/docs ) it is marked as VAD, so that was also my intention for the restructure:

Does Snowboy come with VAD?
Yes, Snowboy comes with Voice Activity Detection. Usually detecting whether there’s human voice in the audio needs much less resource than detecting a hotword. Thus VAD serves as a filtering layer before hotword detection to reduce CPU usage.

How to use Snowboy’s VAD to detect voice and silence?
The return value of SnowboyDetect.RunDetection() function indicates silence, voice, error, and triggered words:

return  meaning
-2  silence
-1  error
0   voice
1,..    triggered index

**Comment by Flowr-es** [comment]
So if Snowboy comes with VAD, I think the API should support it. Noise would be wrong, because it actually detects voice, but maybe the documentation is wrong.
Also I think than voiceactivity should be the emitted topic and the voiceactivity status (silence, voice) is the value. This makes it easy to start and stop recording listening to this state.

Please feel free to close this pull request, if Snowboy has no VAD or you don't want to change the interface like this.

**Comment by evancohen** [comment]
@MexXxo I think this would be worth brining up in the open PR we have on the snowboy repo. I think you are probubly right, but since they have already reviewed it I don't want to be sneaking in additional changes.

**Pull request closed without merging**
